version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '07:00'
      timezone: 'America/Los_Angeles'
    open-pull-requests-limit: 0
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'npm'
    assignees:
      - 'pdugan20'
    reviewers:
      - 'pdugan20'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '07:10'
      timezone: 'America/Los_Angeles'
    open-pull-requests-limit: 0
    commit-message:
      prefix: 'ci'
    labels:
      - 'dependencies'
      - 'github-actions'
    assignees:
      - 'pdugan20'
    reviewers:
      - 'pdugan20'
